kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- postgresql.yaml

configMapGenerator:
- literals:
  - postgres_version=latest
  name: postgres-version


images:
  - name: postgres
    newName: docker.io/bitnami/postgresql
    newTag: "14.10.0"  # Set your desired Postgres version here
