kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: selfservice-ui-env
    envs:
      - config/selfservice-ui.env
