kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: admin-ui-env
    envs:
      - config/admin-ui.env
    files:
      - config.json=config/config.json
      
