# Source: kratos/templates/service-admin.yaml
apiVersion: v1
kind: Service
metadata:
  name: admin-ui
  namespace: default
  labels:
    app.kubernetes.io/name: admin-ui
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: admin-ui
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: admin-ui
