log:
  level: debug
  format: json_pretty

serve:
  proxy:
    port: 4455
    cors:
      enabled: true
      allowed_origins:
        - "http://ory-admin.test.info"
        - "http://ory.test.info"
        - "http://*.test.info"
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
      exposed_headers:
        - Content-Type
      allow_credentials: true
      debug: true
  api:
    port: 4456

errors:
  fallback:
    - json
  handlers:
    redirect:
      enabled: true
      config:
        to: http://ory.test.info/panel/welcome
        when:
          - error:
              - unauthorized
              - forbidden
            request:
              header:
                accept:
                  - text/html
    json:
      enabled: true
      config:
        verbose: true

access_rules:
  matching_strategy: glob
  repositories:
    - file:///etc/rules/access-rules.yaml

authenticators:
  anonymous:
    enabled: true
    config:
      subject: guest
  cookie_session:
    enabled: true
    config:
      check_session_url: http://test-kratos-public:4433/sessions/whoami
      preserve_path: true
      extra_from: "@this"
      subject_from: "identity.id"
      only:
        - ory_kratos_session
  noop:
    enabled: true

authorizers:
  allow:
    enabled: true
  remote_json:
    enabled: true
    config:
      remote: http://keto-api:4456/check
      payload: |
        {
          "subject": "{{ print .Subject }}",
          "resource": "{{ printIndex .MatchContext.RegexpCaptureGroups 0 }}"
        }

mutators:
  noop:
    enabled: true
  header:
    enabled: true
    config:
      headers:
        X-General: Consulting
  id_token:
    enabled: true
    config:
      issuer_url: http://ory.test.info/panel/
      jwks_url: file:///etc/config/oathkeeper/id_token.jwks.json
      claims: |
        {
          "session": {{ .Extra | toJson }}
        }
